.TH GETENT 1 "fixture" "fixture"
.SH "NAME"
getent \- get entries from Name Service Switch libraries
.SH "SYNOPSIS"
.B getent
.RI [ option ]...
.I database
.RI [ key "]..."
.SH "DESCRIPTION"
The
.B getent
command displays entries from databases supported by the Name Service
Switch libraries. The
.I database
may be any of the following:
.TP
.B passwd
When no
.I key
is provided, use setpwent(3).
.TP
.B group
Group database.
.TP
.B hosts
Host name and address database.
.SH "OPTIONS"
.TP
.B \-s\fR,\fB \-\-service\fR=\fICONFIG\fR
Override all databases with the specified service.
.TP
.B \-\-no\-idn
Disables IDN encoding in lookups.
.TP
.B \-?\fR,\fB \-\-help\fR
Print a usage message.
