.TH WIDGET 1 "fixture" "fixture"
.SH NAME
widget \- manage widgets
.SH SYNOPSIS
.B widget
.RI [ OPTIONS ]
.I COMMAND
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose logging.
.TP
\fB\-\-config\fR=\fIPATH\fR
Use the given config file.
.SH COMMANDS
.TP
.B create
Create a new widget.
.TP
.B list
List existing widgets.
.TP
.B remove
Remove a widget by name.
